"use client";
import {useEffect,useState} from "react";
import {Search,MapPin,Bookmark,ArrowUpRight,SlidersHorizontal,BriefcaseBusiness,Monitor,ArrowRight,Database,Check,RotateCcw} from "lucide-react";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Checkbox} from "@/components/ui/checkbox";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from "@/components/ui/empty";
import {fold,type Job} from "@/lib/jobs";
function Picker({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <div className="filtergroup"><label>{label}</label><Select value={value} onValueChange={set}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{["Todos",...options].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>}
export default function Home(){
const [view,setView]=useState("explore"),[jobs,setJobs]=useState<Job[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saved,setSaved]=useState<string[]>([]),[saveReady,setSaveReady]=useState(false),[busy,setBusy]=useState<string|null>(null),[selected,setSelected]=useState<Job|null>(null);
const [query,setQuery]=useState(""),[location,setLocation]=useState(""),[country,setCountry]=useState("Brasil"),[level,setLevel]=useState("Todos"),[type,setType]=useState("Todos"),[mode,setMode]=useState("Todos"),[area,setArea]=useState("Todos"),[source,setSource]=useState("Todos"),[salary,setSalary]=useState(false),[filtersOpen,setFiltersOpen]=useState(false),[sort,setSort]=useState("Recentes");
async function reload(){setLoading(true);setError("");try{const r=await fetch("/api/jobs");if(!r.ok)throw Error("Não foi possível carregar as vagas reais. Tente novamente.");setJobs((await r.json() as {jobs:Job[]}).jobs);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
useEffect(()=>{reload();fetch("/api/favorites").then(async r=>{if(!r.ok)throw Error();setSaved((await r.json() as {ids:string[]}).ids);setSaveReady(true);}).catch(()=>setError("Não foi possível carregar seus favoritos. Recarregue a página para tentar novamente."));},[]);
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const ac=new AbortController();Promise.resolve(ctx.registerTool({name:"filter_jobs",description:"Atualiza a busca de vagas exibida na página.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(typeof input?.query!=="string"||input.query.length>200)throw Error("Busca inválida");setQuery(input.query);setView("explore");return{query:input.query};}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort();},[]);
async function toggle(j:Job){setBusy(j.id);try{const next=!saved.includes(j.id);const r=await fetch("/api/favorites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({job:j.id,saved:next})});if(!r.ok)throw Error();setSaved(s=>next?[...s,j.id]:s.filter(id=>id!==j.id));}catch{setError("Não foi possível salvar. Seu favorito não foi alterado; tente novamente.");}finally{setBusy(null);}}
function clear(){setQuery("");setLocation("");setCountry("Brasil");setLevel("Todos");setType("Todos");setMode("Todos");setArea("Todos");setSource("Todos");setSalary(false);}
let list=jobs.filter(j=>fold(j.title+" "+j.company+" "+j.tags.join(" ")).includes(fold(query))&&fold(j.location).includes(fold(location))&&(level==="Todos"||j.level===level)&&(type==="Todos"||j.type===type)&&(mode==="Todos"||j.mode===mode)&&(area==="Todos"||j.area===area)&&(source==="Todos"||j.source===source)&&(country==="Todos"||j.country===country)&&(!salary||!fold(j.salary).includes("nao informado"))&&(view!=="saved"||saved.includes(j.id)));
if(sort==="Título A–Z")list=[...list].sort((a,b)=>a.title.localeCompare(b.title,"pt-BR"));
const count=[level,type,mode,area,source,country].filter(v=>v!=="Todos").length+Number(salary);
return <><header className="topbar"><a className="brand" href="/" aria-label="BoraVaga início"><span className="logo">b</span><span>bora<b>vaga</b></span></a><nav aria-label="Navegação principal">{[["explore","Explorar vagas",Search],["saved","Salvas",Bookmark],["sources","Fontes",Database]].map(([key,label,Icon]:any)=><button key={key} className={`navbutton ${view===key?"active":""}`} onClick={()=>setView(key)}><Icon size={16}/>{label}{key==="saved"&&saved.length>0?` (${saved.length})`:""}</button>)}</nav><span className="avatar" title="Projeto acadêmico">BV</span></header>
<main className="wrap"><div className="heading"><div><p className="eyebrow">MENOS ABAS. MAIS POSSIBILIDADES.</p><h1>{view==="saved"?<>Seus próximos <em>passos.</em></>:view==="sources"?<>De onde vêm as <em>vagas.</em></>:<>Seu próximo passo <em>começa aqui.</em></>}</h1><p className="sub">{view==="saved"?"As oportunidades que você quer acompanhar.":view==="sources"?"Acompanhe a disponibilidade de cada portal.":"Encontre oportunidades que combinam com o seu momento."}</p></div><span className="demo-label">Projeto em desenvolvimento</span></div>
{view==="sources"?<><div className="notice">A coleta automática ainda não está ativa. Os portais abaixo estão planejados; nenhum anúncio deles foi importado nesta versão.</div><div className="sources">{[["Indeed","https://br.indeed.com/"],["InfoJobs","https://www.infojobs.com.br/"],["LinkedIn","https://www.linkedin.com/jobs/"],["Catho","https://www.catho.com.br/"]].map(([name,url])=><article className="sourcecard" key={name}><h2>{name}</h2><span className="chip">Integração pendente</span><p>Coleta e regras de acesso ainda precisam ser validadas. Última coleta: não realizada.</p><a className="detailslink" href={url} target="_blank" rel="noopener noreferrer">Visitar portal <ArrowUpRight size={16}/></a></article>)}</div></>:<>
<form className="searchbar" onSubmit={e=>{e.preventDefault();document.getElementById("results")?.scrollIntoView({behavior:"smooth",block:"start"});}}><label className="searchfield"><Search size={20}/><input aria-label="Cargo, empresa ou palavra-chave" placeholder="Cargo, empresa ou palavra-chave" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="searchfield"><MapPin size={20}/><input aria-label="Cidade ou estado" placeholder="Cidade ou estado" value={location} onChange={e=>setLocation(e.target.value)}/></label><button className="primary" type="submit">Buscar vagas <ArrowRight size={17}/></button></form>
<div className="quick"><span>Um atalho pra você:</span><button className={`chip ${type==="Estágio"?"on":""}`} onClick={()=>setType(type==="Estágio"?"Todos":"Estágio")}>Meu primeiro estágio</button><button className={`chip ${level==="Júnior"?"on":""}`} onClick={()=>setLevel(level==="Júnior"?"Todos":"Júnior")}>Vagas júnior</button><button className={`chip ${mode==="Remoto"?"on":""}`} onClick={()=>setMode(mode==="Remoto"?"Todos":"Remoto")}>100% remoto</button></div>
<button className="filtertoggle" onClick={()=>setFiltersOpen(!filtersOpen)} aria-expanded={filtersOpen}><SlidersHorizontal size={17}/>Filtros {count?`(${count})`:""}</button>
<div className="workspace"><aside className={`filters ${filtersOpen?"open":""}`}><div className="filterhead"><h2>Filtros {count?`· ${count}`:""}</h2><button className="textbutton" onClick={clear}>Limpar</button></div><Picker label="Nível de experiência" value={level} set={setLevel} options={["Júnior","Pleno","Sênior","Não informado"]}/><Picker label="Tipo de contratação" value={type} set={setType} options={["Estágio","CLT","PJ","Temporário","Não informado"]}/><Picker label="Modalidade" value={mode} set={setMode} options={["Remoto","Híbrido","Presencial","Não informado"]}/><Picker label="Área de atuação" value={area} set={setArea} options={["Tecnologia","Dados","Design","Marketing","Administração","Não informado"]}/><Picker label="País" value={country} set={setCountry} options={["Brasil","Exterior"]}/><Picker label="Fonte" value={source} set={setSource} options={["Greenhouse","Lever","Workable","BreezyHR","Recruitee","SmartRecruiters","Gupy","Personio"]}/><div className="filtergroup"><label className="filterline"><Checkbox checked={salary} onCheckedChange={v=>setSalary(v===true)}/>Com salário informado</label></div><p className="aside-note">Cada carreira tem seu ritmo.<br/>Encontre o seu próximo passo.</p></aside>
<section id="results" aria-label="Resultados da busca">{error&&<div role="alert" className="error">{error} <button onClick={reload}>Tentar carregar vagas novamente</button></div>}<div className="resultshead"><div><h2 aria-live="polite">{list.length} {list.length===1?"oportunidade encontrada":"oportunidades encontradas"}</h2><small>{view==="saved"?"Favoritos vinculados a este navegador":"Um lugar para encontrar seu próximo trabalho"}</small></div><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Ordenar vagas"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Recentes">Recentes</SelectItem><SelectItem value="Título A–Z">Título A–Z</SelectItem></SelectContent></Select></div>
{loading?<p role="status">Carregando vagas…</p>:list.length===0?<Empty className="empty"><EmptyHeader><Search size={30}/><EmptyTitle>{jobs.length===0?"Nenhuma vaga real carregada":view==="saved"?"Nenhuma vaga salva nesta busca":"Nenhuma vaga com esses filtros"}</EmptyTitle><EmptyDescription>{jobs.length===0?"As vagas brasileiras aparecerão aqui quando os feeds públicos responderem.":"Experimente mudar a busca ou limpar os filtros."}</EmptyDescription></EmptyHeader><button className="primary" onClick={()=>{clear();reload();}}>Atualizar vagas</button></Empty>:list.map((j,i)=><article className="jobcard" key={j.id}><div className="jobtop"><div className="companymark">{j.company.slice(0,1)}</div><div><button className="jobtitle" onClick={()=>setSelected(j)}>{j.title}</button><p className="companyname">{j.company}</p></div><button className={`bookmark ${saved.includes(j.id)?"saved":""}`} disabled={!saveReady||busy===j.id} onClick={()=>toggle(j)} aria-label={`${saved.includes(j.id)?"Remover dos favoritos":"Salvar vaga"}: ${j.title}`} aria-pressed={saved.includes(j.id)}><Bookmark size={20} fill={saved.includes(j.id)?"currentColor":"none"}/></button></div><div className="metadata"><span><MapPin size={14}/>{j.location}</span><span><Monitor size={14}/>{j.mode}</span><span><BriefcaseBusiness size={14}/>{j.salary}</span></div><div className="tags">{j.level!=="Não informado"&&<span className="tag purple">{j.level}</span>}<span className="tag green">{j.type}</span>{j.tags.map(t=><span className="tag" key={t}>{t}</span>)}</div><div className="jobbottom"><span>{j.demo?"Exemplo fictício":`${j.source} · Verificada em ${new Date(j.checked).toLocaleDateString("pt-BR")}`}</span><button className="detailslink" onClick={()=>setSelected(j)}>Ver vaga <ArrowUpRight size={15}/></button></div></article>)}
</section></div></>}
<footer className="footer"><span>bora<strong>vaga</strong> · Projeto acadêmico</span><span>Feito para o seu próximo passo.</span></footer></main>
<Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><SheetContent className="w-full sm:max-w-lg overflow-y-auto"><SheetHeader className="pt-12 px-7"><span className="eyebrow">{selected?.demo?"VAGA DE DEMONSTRAÇÃO":selected?.source}</span><SheetTitle className="text-2xl leading-tight">{selected?.title}</SheetTitle><SheetDescription>{selected?.company} · {selected?.location}</SheetDescription></SheetHeader>{selected&&<div className="detailbody"><div className="tags"><span className="tag purple">{selected.level}</span><span className="tag green">{selected.type}</span><span className="tag">{selected.mode}</span></div><h3>Remuneração</h3><p>{selected.salary}</p><h3>Sobre a oportunidade</h3><p className="whitespace-pre-wrap">{selected.description}</p><h3>Conhecimentos</h3><div className="tags">{selected.tags.map(t=><span className="tag" key={t}>{t}</span>)}</div><div className="mt-8 flex flex-col gap-3">{selected.demo?<div className="notice">Este é um exemplo fictício. Não aceita candidaturas.</div>:<a className="primary" href={selected.url} target="_blank" rel="noopener noreferrer">Candidatar-se no portal <ArrowUpRight size={18}/></a>}<button className="primary" disabled={!saveReady||busy===selected.id} onClick={()=>toggle(selected)}><Bookmark size={16}/>{saved.includes(selected.id)?"Remover dos favoritos":"Salvar oportunidade"}</button></div></div>}</SheetContent></Sheet>
</>}
